---
# facts for revboot.regional.chrony
# See https://redhat-cop.github.io/automation-good-practices

- name: "Ensure ansible_facts used by role"
  ansible.builtin.setup:
    gather_subset: 'min'
  when: not ansible_facts.keys() | list

- name: "Set platform/version specific variables"
  ansible.builtin.include_vars: "{{ __chrony_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    __chrony_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __chrony_vars_file is file
